### ISSUE TITLE
Unable for manual deploy

### ISSUE THREAD

**Issue by mattijshappe** [SAP-samples/btp-side-by-side-extension-learning-journey#29]
Hello,

During the manual deployment step, the deployment runs into an error:
Uploading 1 files...
  /home/user/projects/risk-management/gen/mta.tar
OK
Operation ID: ff6f4094-7adf-11ed-a094-eeee0a8f457b
Deploying in org "Ctac N.V. Free Tier (Pay As You Go)_ctac01" and space "dev"
Detected MTA schema version: "3"
Detected deployed MTA with ID "risk-management" and version "2.0.0"
Detected new MTA version: "2.0.0"
Deployed MTA version: "2.0.0"
Processing service "risk-management-db"...
Updating service "risk-management-db"...
Processing service "risk-management-auth"...
Setting service "risk-management-auth" parameters from "xs-security.json"
Updating service "risk-management-auth"...
1 of 1 done
1 of 1 done
Updating application "risk-management-db-deployer"...
Updating application "risk-management-srv"...
Updating application "risk-management"...
Unbinding service instance "risk-management-db" from application "risk-management-db-deployer"...
Binding service instance "risk-management-db" to application "risk-management-db-deployer"...
Unbinding service instance "risk-management-db" from application "risk-management-srv"...
Unbinding service instance "risk-management-auth" from application "risk-management"...
Binding service instance "risk-management-db" to application "risk-management-srv"...
Unbinding service instance "risk-management-auth" from application "risk-management-srv"...
Binding service instance "risk-management-auth" to application "risk-management"...
Uploading application "risk-management-db-deployer"...
Binding service instance "risk-management-auth" to application "risk-management-srv"...
Uploading application "risk-management-srv"...
Started async upload of application "risk-management-db-deployer"
Uploading application "risk-management"...
Started async upload of application "risk-management-srv"
Started async upload of application "risk-management"
Stopping application "risk-management"...
Stopping application "risk-management-db-deployer"...
Stopping application "risk-management-srv"...
Staging application "risk-management"...
Staging application "risk-management-srv"...
Staging application "risk-management-db-deployer"...
Application "risk-management" staged
Starting application "risk-management"...
Application "risk-management-db-deployer" staged
Application "risk-management-srv" staged
Starting application "risk-management-srv"...
Executing task "deploy" on application "risk-management-db-deployer"...
Application "risk-management-srv" started and available at "ctac-n-v--free-tier--pay-as-you-go--ctac01-dev-risk-manad9ae7a0.cfapps.eu10-004.hana.ondemand.com"
Application "risk-management" started and available at "ctac-n-v--free-tier--pay-as-you-go--ctac01-dev-risk-management.cfapps.eu10-004.hana.ondemand.com"
Execution of task "deploy" on application "risk-management-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Proceeding with automatic retry... (3 of 3 attempts left)
Executing task "deploy" on application "risk-management-db-deployer"...
^[`Execution of task "deploy" on application "risk-management-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Proceeding with automatic retry... (2 of 3 attempts left)
Executing task "deploy" on application "risk-management-db-deployer"...
Execution of task "deploy" on application "risk-management-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Proceeding with automatic retry... (1 of 3 attempts left)
Executing task "deploy" on application "risk-management-db-deployer"...
Execution of task "deploy" on application "risk-management-db-deployer" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Process failed.
Use "cf deploy -i ff6f4094-7adf-11ed-a094-eeee0a8f457b -a abort" to abort the process.
Use "cf deploy -i ff6f4094-7adf-11ed-a094-eeee0a8f457b -a retry" to retry the process.
Use "cf dmol -i ff6f4094-7adf-11ed-a094-eeee0a8f457b" to download the logs of the process.

In the BTP cokpit logs of Application: risk-management-db-deployer -:
Deployment to container undefined failed - error: Connection failed (RTE:[-1] Kerberos error. Major: "unspecified [851968]", minor: "No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_2000) [2529639053/-1765328243]" (10.140.121.207:37542 -> 7694b180-0ccd-422d-96fd-a945767c3722.hna1.prod-eu10.hanacloud.ondemand.com:443)) [Deployment ID: none].

Applications 
risk-management and risk-management-srv are running correctly.

What am I doing wrong?
Thnx!

**Comment by markushaug** [comment]
Hi, 

please use our [SAP Learning Community Groups](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning) for support requests.

However, we need your complete logs. Please export the log via:
```bash
cf dmol -i ff6f4094-7adf-11ed-a094-eeee0a8f457b
```
You can run this command in your BAS terminal.

Thanks,
Markus
