### ISSUE TITLE
Unit 3: Business Partner Value list doesn't work when trying to choose a BP

### ISSUE THREAD

**Issue by mahajan-nitin** [SAP-samples/btp-side-by-side-extension-learning-journey#35]
> **NOTE:** Please do not open issues if you are seeking for support for the learning journey! Please use the dedicated [SAP BTP Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning) instead.

**Describe the bug**
Business Partner Value list doesn't work

**To Reproduce**
Create a new Risk and try to choose a Business Partner, nothing is removed

**Expected behavior**
List of Business Partners should be returned

**Screenshots**
![Screenshot 2023-01-29 at 1 35 16 PM](https://user-images.githubusercontent.com/118976022/215313832-a292210d-2c93-49ac-83ec-ce40c58d0e01.png)

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
The problem seems to come from $count=true getting appended to the query. Ran the query without this (via Postman) and it worked.
Not sure how it gets added and how can one remove it as this seems to be getting added automatically.

https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER//A_BusinessPartner?$select=BusinessPartner,FirstName,LastName&$count=true&$top=69&$orderby=LastName%20asc,BusinessPartner%20asc&$filter=LastName%20ne%20''%20and%20FirstName%20ne%20''

**Comment by markushaug** [comment]
Hi, thanks for your input. You've might already have seen, that we've provided a code snippet in the community group to fix this issue.
