### ISSUE TITLE
Fiori Elements exercise error with SAPUI5 Flexibility Service / Layered Repository

### ISSUE THREAD

**Issue by torresbj** [SAP-samples/btp-side-by-side-extension-learning-journey#51]
**Describe the bug**
The fiori elements page after generation did not load successfully as it's missing a component in the new version of fiori elements generator

**To Reproduce**
1. Go to Open Application Generator and Generate a Fiori Elements List Report page (User Interface and Business Logic -> Generating User Interface -> Step 1
2. Run cds watch
3. Click on Web Applications -> /risks/webapp/index.html

**Expected behavior**
Page will load successfully

**Actual behavior**
Page did not load as two services failed 

/sap/bc/lrep/flex/settings
Cannot GET /sap/bc/lrep/flex/settings

sap/bc/lrep/flex/data/risks?sap-language=EN
Cannot GET /sap/bc/lrep/flex/data/risks

**Screenshots**

![image](https://user-images.githubusercontent.com/12954079/235868341-6011547b-3845-4539-8353-76cf876cdfe3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOSX
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by torresbj** [comment]
It was resolved by installing [lrep-flex](https://www.npmjs.com/package/ui5-middleware-lrep-flex) with the steps in the URL and adding data-sap-ui-flexibilityServices='[{"connector": "LocalStorageConnector"}]' after a few tries

**Comment by markushaug** [comment]
Hi, 

kindly add your inquiry to our dedicated [Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning). We do not provide support for the exercises on GitHub.

Best Regards,
Markus

**Comment by ambhavesh** [comment]
> I was able to resolve it by adding data-sap-ui-flexibilityServices='[{"connector": "LocalStorageConnector"}]' in the index.html
> 
> ![image](https://user-images.githubusercontent.com/12954079/236119268-8aec64f4-423b-4a2b-a50e-ef62051b8c9c.png)

Hi Torresbj,

That is only working locally. After deployment it's not working do you have any solution?
