### ISSUE TITLE
Couldn't find a CDS model for '*' in /home/user/projects/risk-management

### ISSUE THREAD

**Issue by croy27** [SAP-samples/btp-side-by-side-extension-learning-journey#61]
> **NOTE:** Please do not open issues if you are seeking for support for the learning journey! Please use the dedicated [SAP BTP Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning) instead.

**Describe the bug**
Couldn't find a CDS model for '*' in /home/user/projects/risk-management

**To Reproduce**
1. clone
2. npm ci
3. cds watch

**Expected behavior**
No errors.

**Screenshots**
<img width="1238" alt="2023-07-21_12-05-58" src="https://github.com/SAP-samples/btp-side-by-side-extension-learning-journey/assets/34281332/9b4ae1c2-77fc-423e-80f3-c41aa2e77e72">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave
 - Version: latest and greatest

**Comment by markushaug** [comment]
Hi, 

kindly add your inquiry to our dedicated [Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning). We do not provide support for the exercises on GitHub.

Best Regards,
Markus
