### ISSUE TITLE
No Options in SAP HANA Database Availability Zone and Replicas Screen

### ISSUE THREAD

**Issue by shabirmd** [SAP-samples/btp-side-by-side-extension-learning-journey#63]
While learning Course "Building side-by-side extensions on SAP BTP", in chapter 4, Sub section one - "Performing manual Deployment", it has steps to select Zone in Screen "SAP HANA Database Availability Zone and Replicas ". When I perform this, its empty and doesn't given option to select anything. the screen is blank except at warning which says "
Deploying replicas is not available for SAP HANA Cloud Trial instances."

If i continue to create Db instance with this, it starts but crashes abruptly. The Training shows we need to "You have to select an availability zone for the SAP HANA Cloud Database. Confirm the default settings by clicking on Next Step." but there is nothing to select. Kindly advise.

**Comment by markushaug** [comment]
Hi, 

kindly add your inquiry to our dedicated [Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning). We do not provide support for the exercises on GitHub.

Best Regards,
Markus
