### ISSUE TITLE
Deployment does not work at all

### ISSUE THREAD

**Issue by sfdfklskldf** [SAP-samples/btp-side-by-side-extension-learning-journey#67]
**Describe the bug**
Deployment of the app does not work.
As mentioned in the README and TROUBLESHOOTING file an upgrade of the NPM packages would be helpful.
At least this seems to solve some issues.

Anyhow the command mentioned in the learning
``cds compile srv/ --to xsuaa > xs-security.json``
produces an empty xs-security.json.

Looking like this:
'''
{
  "scopes": [  ],
  "attributes": [],
  "role-templates": [ ]
}
'''
Deployment fails with error:

Service broker error: Service broker xsuaa failed with: Error creating application null (Error parsing xs-security.json data: Inconsistent xs-security.json: Invalid xsappname ...

Beside that you have a typo here (TROUBLESHOOTING.md)

The ``uaa`` or nowadays ``auth`` resource should like like this:

Should probably be 

The ``uaa`` or nowadays ``auth`` resource should look like this:

It took me a lot of time to get the deployment done.

Things to do:
1) update all npm packages
2) of course ensure you have a runing hana instance that allows to create hdi
3) implement all hints in TROUBLESHOOTING.md
4) adapt redirect uri
5) maybe you fight with issues if your org has a sapce in the the name (you can not use ${org}
6) adapt the service paths with /odata/v4/ because they moved
7) And there as an issue with
```
       "dependencies": {
...
+        "@sap/cds-dk": "^7",
       },
       "devDependencies": {
-        "@sap/cds-dk": "^7",
```
I had to move it to dependencies otherwise build on CI/CD faild.

All in all would be nice the example would be updated.

**Comment by markushaug** [comment]
Hi, 

kindly add your inquiry to our dedicated [Learning Community Group](https://groups.community.sap.com/t5/sap-btp-learning/gh-p/SAP-BTP-Learning). We do not provide support for the exercises on GitHub.

Best Regards,
Markus
