### ISSUE TITLE
Feature request: Show a working example of multitenancy

### ISSUE THREAD

**Issue by sfdfklskldf** [SAP-samples/btp-side-by-side-extension-learning-journey#69]
The course does not cover one of the main parts *multitenancy*.

I tried to convert this example to a multitenancy version but it seems not working correct.

According to:
https://cap.cloud.sap/docs/guides/multitenancy/

It should be more or less enougth to run
```
cds add multitenancy
```

But I see issues with authentification (get a prompt from HANA DB and not from the ID Provider).
Also completely missig is the topic of creating routes.

Here I see two issues:

1) How to route between regions?
2) What to do if the default-urls are too long?

From my point of view the multitenancy topic must be part of such a course!

**Comment by markushaug** [comment]
Hi Josef,

thanks for your feedback! I highly appreciate it.

I have good news: Multitenancy is already in the backlog and the next release of the content will have it. So stay tuned! If you have any other tips for improvements, kindly let me know.

BR,
Markus

**Comment by sfdfklskldf** [comment]
Meanwhile I could figure out how to get it running. But it cost a lot of time and experiments.
Which contradicts the CAP concept somehow.
I would wish SAP is more clear on documentation what is currently not working or in progress or what could lead to issues.

Just to compare, I need over a week to get the "example" running. But just 2-3 days implement a full working multi tenant app manually using NodeJS + PostgerSQL. Of course with the lack of some CAP generated stuff which would speed up real development in the OData / Fiori environment but not everything fits in this template.

Further topics I miss:
1) File handling (upload/download) - some apps need to upload/download files. Here I could not find the "best practice" approche with CAP.
Files could be binary or maybe some text based files (JSON for example or CSV) that could be processed in the backend in some way. Would be very nice to have a interface that is easy to use with the FileUploader in SAPUI5 for example.

2) How should the app delivered with CAP project be integrated in the Fiori Launchpad (aka [SAP Build Work Zone, standard edition] and others)? I could not find a good example here.
